### ISSUE TITLE
Reason behind such large images?

### ISSUE THREAD

**Issue by michaelherold** [guard/notiffany#12]
I run a mimimalist window manager with [dunst][dunst] as my notification daemon. That daemon currently does not currently support resizing icons via a maximum size. That being said, what is the reasoning for such large icons? It makes Guard's notifications essentially unusable for me, since they're not resized by the daemon.

It seems like they should be smaller by default, particularly since the size they currently are requires resizing for any sort of notification.

Note: I also filed a feature request with them, so I'm following up on both fronts.

[dunst]: https://github.com/knopwob/dunst

**Comment by e2** [comment]
These images were added here (explained): https://github.com/guard/notiffany/pull/10

You can always specify an alternative folder with images - or alternative images altogether.

Scaling images is probably the way to go - since various devices have different densities and dimensions.

I could revert the previous icons and add them as an alternative theme.

**Comment by michaelherold** [comment]
Oh ... yeah ... We're looking at a git repo aren't we? :flushed: Thanks for pointing out the PR!

I guess it's time to brush up on my C and patch my notification daemon. Though I do agree with your suggestion from the other PR to switch to SVG files instead of large PNGs (even though that too would require some work in my daemon, haha). Is that still something that you'd like to pursue?

**Comment by e2** [comment]
I'd happily accept PR for alternative icon themes (PNG, SVG, large, small) - as long as the files aren't huge. Even the old PNG files can be reverted (and placed in another directory).

It doesn't make sense for me to do this myself, since I don't use the notifications myself.

But I'll gladly accept PRs and release updates.
